# Metadata Registry Configuration

# Storage configuration
storage:
  path: "${STORAGE_PATH:-./data}"
  persistence: true

# Service discovery configuration
discovery:
  # Automatic discovery on startup
  auto_discover: true
  
  # Feeds for discovering services
  feeds:
    # Local filesystem feed - discovers services from YAML/JSON files
    - name: "local_files"
      type: "file"
      enabled: true
      directory: "${SERVICES_DIR:-./data/services}"
      pattern: "*.{json,yaml,yml}"
      poll_interval: 30  # Check for changes every 30 seconds
    
    # HTTP feed - discovers services from remote endpoints
    - name: "http_registry"
      type: "http"
      enabled: true
      urls:
        - "${SERVICE_REGISTRY_URL:-http://localhost:8235/services}"
      poll_interval: 300  # Poll every 5 minutes
    
    # Plugin feed - discovers services from Python modules
    - name: "plugins"
      type: "plugin"
      enabled: true
      plugin_dirs:
        - "${PLUGIN_DIR:-./plugins}"
      pattern: "*_service.py"

# Trust and security
trust:
  enabled: true
  auto_verify: "${AUTO_VERIFY:-true}"  # Auto-verify local services for development
  consent_required: "${CONSENT_REQUIRED:-false}"  # Whether user consent is required for operations
  
# Server configuration
server:
  host: "${HOST:-0.0.0.0}"
  port: "${PORT:-8234}"
  debug: "${DEBUG:-false}"

# Neo4j configuration (used if Neo4j is the default service)
neo4j:
  uri: "${NEO4J_URI:-neo4j://localhost:7687}"
  username: "${NEO4J_USER:-neo4j}"
  password: "${NEO4J_PASSWORD:-neo4j}"